version: "3"
services:   # Defines containers to be built when run

 client:    # Defines the hostname of the container internally
            # This allows for container networking using this name
     build: ./client    # Defines the directory containing the Dockerfile to be built
     restart: always    # Defines behaviour for availability
     container_name: client     # Defines the container name within docker for readability
     ports:
     - "8080:8080"      # Maps container port (right) to host system port (left)
 server:
     build: ./server
     restart: always
     container_name: server
     env_file: ./server/.env.example    # Defines environment file to use (i.e. .env in node)
     ports:
     - "3001:3001"
     depends_on:
        - dbcontainer   # Will not build server until dbcontainer is built
 dbcontainer:
     image: mysql:5.6   # Pulls the official mysql image from dockerhub
     restart: always
     command: --default-authentication-plugin=mysql_native_password     # Required compatibility for knex (node plugin)
     container_name: dbcontainer
     environment:       # Sets environment variables inside the container
        MYSQL_DATABASE: sitedb
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbpass
        MYSQL_ROOT_PASSWORD: password
     ports:
     - "27017:3306"