version: "3"
services:
 client:
     build: ./client
     restart: always
     container_name: client
     ports:
     - "8080:8080"
 server:
     build: ./server
     restart: always
     container_name: server
     env_file: ./server/.env.example
     ports:
     - "3001:3001"
     depends_on:
        - dbcontainer
 dbcontainer:
     image: mysql:5.6
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     container_name: dbcontainer
     environment:
        MYSQL_DATABASE: sitedb
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbpass
        MYSQL_ROOT_PASSWORD: password
     ports:
     - "27017:3306"