name: Run Server test suite
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
        working-directory: ./server
      - name: Run Migrations
        run: ./node_modules/.bin/knex migrate:latest
        working-directory: ./server
      - name: Run Tests
        run: yarn test
        working-directory: ./server
        env:
          CI: true
          NODE_ENV: test
          DUMMY_PASSWORD: ${{ secrets.DUMMY_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SALT_ROUNDS: 10
